---

name: build
on:
  #push:
   # branches:
    #  - master
  pull_request:
  schedule:
    - cron: '25 4 * * 4'
  workflow_dispatch:

jobs:
  build-base:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Build base container
        uses: ./.github/actions/build-single-container
        with:
          tag: latest
          github_token: ${{ secrets.GITHUB_TOKEN }}

  layer-one-images:
    runs-on: ubuntu-latest
    needs: build-base
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    strategy:
      matrix:
        tag: [with-node, with-deno, with-chromedriver]
        base: [latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Build layer one images
        uses: ./.github/actions/build-single-container
        with:
          tag: ${{ matrix.tag }}
          base: ${{ matrix.base }}
          github_token: ${{ secrets.GITHUB_TOKEN }}

  layer-two-images:
    runs-on: ubuntu-latest
    needs: layer-one-images
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    strategy:
      matrix:
        tag: [with-playwright, with-puppeteer, with-selenoid]
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Build layer two images
        uses: ./.github/actions/build-single-container
        with:
          tag: ${{ matrix.tag }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
